# Generated by Django 5.2.4 on 2026-07-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_savedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaking_alerts', to='news.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
